### ISSUE TITLE
Tried Installing on Pop OS, getting this error

### ISSUE THREAD

**Issue by Mesum-Hussain** [jbuchermn/pywm#13]
I tried installing on Pop OS 22.04 with 
`pip3 install --user git+https://github.com/jbuchermn/pywm` 

and getting this error: 
```
Collecting git+https://github.com/jbuchermn/pywm
  Cloning https://github.com/jbuchermn/pywm to /tmp/pip-req-build-1wc7rr0h
  Running command git clone --filter=blob:none --quiet https://github.com/jbuchermn/pywm /tmp/pip-req-build-1wc7rr0h
  Resolved https://github.com/jbuchermn/pywm to commit 8171cd7055465544333bab0d3ac22b68da718d48
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-1wc7rr0h/setup.py", line 9, in <module>
          raise Exception("Fatal: Error executing 'meson build': \n%r\n%r" % (stdout, stderr))
      Exception: Fatal: Error executing 'meson build':
      b'The Meson build system\nVersion: 0.61.2\nSource dir: /tmp/pip-req-build-1wc7rr0h\nBuild dir: /tmp/pip-req-build-1wc7rr0h/build\nBuild type: native build\nProject name: pywm\nProject version: 0.1.0\nC compiler for the host machine: cc (gcc 11.2.0 "cc (Ubuntu 11.2.0-19ubuntu1) 11.2.0")\nC linker for the host machine: cc ld.bfd 2.38\nHost machine cpu family: x86_64\nHost machine cpu: x86_64\n\nExecuting subproject wlroots \n\nwlroots| Project name: wlroots\nwlroots| Project version: 0.15.0\nwlroots| C compiler for the host machine: cc (gcc 11.2.0 "cc (Ubuntu 11.2.0-19ubuntu1) 11.2.0")\nwlroots| C linker for the host machine: cc ld.bfd 2.38\nwlroots| Compiler for C supports arguments -Wundef: YES\nwlroots| Compiler for C supports arguments -Wlogical-op: YES\nwlroots| Compiler for C supports arguments -Wmissing-include-dirs: YES\nwlroots| Compiler for C supports arguments -Wold-style-definition: YES\nwlroots| Compiler for C supports arguments -Wpointer-arith: YES\nwlroots| Compiler for C supports arguments -Winit-self: YES\nwlroots| Compiler for C supports arguments -Wstrict-prototypes: YES\nwlroots| Compiler for C supports arguments -Wimplicit-fallthrough=2: YES\nwlroots| Compiler for C supports arguments -Wendif-labels: YES\nwlroots| Compiler for C supports arguments -Wstrict-aliasing=2: YES\nwlroots| Compiler for C supports arguments -Woverflow: YES\nwlroots| Compiler for C supports arguments -Wmissing-prototypes: YES\nwlroots| Compiler for C supports arguments -Walloca: YES\nwlroots| Compiler for C supports arguments -Wno-missing-braces: YES\nwlroots| Compiler for C supports arguments -Wno-missing-field-initializers: YES\nwlroots| Compiler for C supports arguments -Wno-unused-parameter: YES\nwlroots| Compiler for C supports arguments -fmacro-prefix-map=/prefix/to/hide=: YES\nwlroots| Found pkg-config: /usr/bin/pkg-config (0.29.2)\nwlroots| Found CMake: /usr/bin/cmake (3.22.1)\nwlroots| Run-time dependency wayland-server found: NO (tried pkgconfig and cmake)\nwlroots| Looking for a fallback subproject for the dependency wayland-server\n\nsubprojects/wlroots/meson.build:101:0: ERROR: Neither a subproject directory nor a wayland.wrap file was found.\n\nA full log can be found at /tmp/pip-req-build-1wc7rr0h/build/meson-logs/meson-log.txt\n'
      b''
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Not able to understand the issue. What could be the problem? What are the possible steps to mitigate it?

**Comment by jbuchermn** [comment]
I can't really tell what's wrong here, can you try v0.3?

**Comment by jbuchermn** [comment]
I just merged v0.3 into master, fyi.

**Comment by mateusfbsoares** [comment]
I'm having the same problem with master in ubuntu 22.04

Command used: pip3 install --user git+https://github.com/jbuchermn/pywm

Full error message:

```
Collecting git+https://github.com/jbuchermn/pywm
  Cloning https://github.com/jbuchermn/pywm to /tmp/pip-req-build-od5gxs73
  Running command git clone --filter=blob:none --quiet https://github.com/jbuchermn/pywm /tmp/pip-req-build-od5gxs73
  Resolved https://github.com/jbuchermn/pywm to commit 6cd58ed216fe5b7448e1dd9321dfc05f591b0fe5
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-od5gxs73/setup.py", line 9, in <module>
          raise Exception("Fatal: Error executing 'meson build': \n%r\n%r" % (stdout, stderr))
      Exception: Fatal: Error executing 'meson build':
      b'The Meson build system\nVersion: 0.61.2\nSource dir: /tmp/pip-req-build-od5gxs73\nBuild dir: /tmp/pip-req-build-od5gxs73/build\nBuild type: native build\nProject name: pywm\nProject version: 0.1.0\nC compiler for the host machine: cc (gcc 11.2.0 "cc (Ubuntu 11.2.0-19ubuntu1) 11.2.0")\nC linker for the host machine: cc ld.bfd 2.38\nHost machine cpu family: x86_64\nHost machine cpu: x86_64\nFound pkg-config: /usr/bin/pkg-config (0.29.2)\nRun-time dependency wayland-server found: YES 1.20.91\nRun-time dependency wayland-client found: YES 1.20.91\nRun-time dependency wayland-cursor found: YES 1.20.91\nRun-time dependency wayland-egl found: YES 18.1.0\nRun-time dependency wayland-protocols found: YES 1.25\nRun-time dependency xkbcommon found: YES 1.4.0\nRun-time dependency libinput found: YES 1.20.0\nRun-time dependency pixman-1 found: YES 0.40.0\nFound CMake: /usr/bin/cmake (3.22.1)\nRun-time dependency xwayland found: NO (tried pkgconfig and cmake)\nLibrary pthread found: YES\nLibrary m found: YES\n\nExecuting subproject wlroots \n\nwlroots| Project name: wlroots\nwlroots| Project version: 0.16.0\nwlroots| C compiler for the host machine: cc (gcc 11.2.0 "cc (Ubuntu 11.2.0-19ubuntu1) 11.2.0")\nwlroots| C linker for the host machine: cc ld.bfd 2.38\nwlroots| Compiler for C supports arguments -Wundef: YES\nwlroots| Compiler for C supports arguments -Wlogical-op: YES\nwlroots| Compiler for C supports arguments -Wmissing-include-dirs: YES\nwlroots| Compiler for C supports arguments -Wold-style-definition: YES\nwlroots| Compiler for C supports arguments -Wpointer-arith: YES\nwlroots| Compiler for C supports arguments -Winit-self: YES\nwlroots| Compiler for C supports arguments -Wstrict-prototypes: YES\nwlroots| Compiler for C supports arguments -Wimplicit-fallthrough=2: YES\nwlroots| Compiler for C supports arguments -Wendif-labels: YES\nwlroots| Compiler for C supports arguments -Wstrict-aliasing=2: YES\nwlroots| Compiler for C supports arguments -Woverflow: YES\nwlroots| Compiler for C supports arguments -Wmissing-prototypes: YES\nwlroots| Compiler for C supports arguments -Walloca: YES\nwlroots| Compiler for C supports arguments -Wno-missing-braces: YES\nwlroots| Compiler for C supports arguments -Wno-missing-field-initializers: YES\nwlroots| Compiler for C supports arguments -Wno-unused-parameter: YES\nwlroots| Compiler for C supports arguments -fmacro-prefix-map=/prefix/to/hide=: YES\nwlroots| Dependency wayland-server found: YES 1.20.91 (cached)\nwlroots| Run-time dependency libdrm found: YES 2.4.110\nwlroots| Run-time dependency gbm found: YES 22.0.1\nwlroots| Dependency xkbcommon found: YES 1.4.0 (cached)\nwlroots| Run-time dependency libudev found: YES 249\nwlroots| Dependency pixman-1 found: YES 0.40.0 (cached)\nwlroots| Library m found: YES\nwlroots| Library rt found: YES\nwlroots| Dependency wayland-protocols found: YES 1.25 (cached)\nwlroots| Found pkg-config: /usr/bin/pkg-config (0.29.2)\nwlroots| Build-time dependency wayland-scanner found: YES 1.20.91\nwlroots| Program /lib/wayland_libs/bin/wayland-scanner found: YES (/lib/wayland_libs/bin/wayland-scanner)\nwlroots| Run-time dependency egl found: YES 1.5\nwlroots| Run-time dependency glesv2 found: YES 3.2\nwlroots| Run-time dependency vulkan found: YES 1.3.204\nwlroots| Check usable header "vulkan/vulkan.h" with dependency vulkan: YES\nwlroots| Program glslangValidator found: NO\nwlroots| Dependency pixman-1 found: YES 0.40.0 (cached)\nwlroots| Checking for function "gbm_bo_get_fd_for_plane" with dependency gbm: YES\nwlroots| Dependency libinput found: YES 1.20.0 (cached)\nwlroots| Run-time dependency xcb found: YES 1.14\nwlroots| Run-time dependency xcb-dri3 found: NO (tried pkgconfig and cmake)\nwlroots| Message: Required for X11 backend support.\nwlroots| Message: Required for X11 backend support.\nwlroots| Dependency wayland-client found: YES 1.20.91 (cached)\nwlroots| Run-time dependency libseat found: YES 0.6.4\nwlroots| Run-time dependency xwayland found: NO (tried pkgconfig and cmake)\nwlroots| Program Xwayland found: YES (/usr/bin/Xwayland)\nwlroots| Dependency xcb found: YES 1.14 (cached)\nwlroots| Run-time dependency xcb-composite found: YES 1.14\nwlroots| Run-time dependency xcb-icccm found: NO (tried pkgconfig and cmake)\nwlroots| Message: Install "xcb-icccm" or pass "-Dxwayland=disabled".\nwlroots| Required for Xwayland support.\n\nsubprojects/wlroots/xwayland/meson.build:36:1: ERROR: Dependency "xcb-icccm" not found, tried pkgconfig and cmake\n\nA full log can be found at /tmp/pip-req-build-od5gxs73/build/meson-logs/meson-log.txt\n'
      b''
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by ImpeccablePenguin** [comment]
I ran `sudo apt install libwlroots-dev libwlroots10` and it fixed this error.

**Comment by Mesum-Hussain** [comment]
> I ran `sudo apt install libwlroots-dev libwlroots10` and it fixed this error. (I'm on Pop_OS 22.04)

That's great!

Any chances of it running on Debian LTS?

Anyways I will try it out on Pop OS.

Thanks.

**Comment by ImpeccablePenguin** [comment]
So far I've only been able to get a black screen. I haven't been available to troubleshoot much today so I've mostly just been trying to get it to work with GDM.
