### ISSUE TITLE
Run-time dependency libseat found: NO

### ISSUE THREAD

**Issue by euglevi** [jbuchermn/pywm#15]
Hello, I am trying to install pywm with pip in a Debian sid machine. However, I get the following error. I have libseat and libseat-dev already installed at the version 0.7.0, so I am not sure what the problem is. I would be happy if someone could help.

```
Collecting git+https://github.com/jbuchermn/pywm
  Cloning https://github.com/jbuchermn/pywm to /tmp/pip-req-build-4ppusefq
  Running command git clone --filter=blob:none --quiet https://github.com/jbuchermn/pywm /tmp/pip-req-build-4ppusefq
  Resolved https://github.com/jbuchermn/pywm to commit 6cd58ed216fe5b7448e1dd9321dfc05f591b0fe5
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-4ppusefq/setup.py", line 9, in <module>
          raise Exception("Fatal: Error executing 'meson build': \n%r\n%r" % (stdout, stderr))
      Exception: Fatal: Error executing 'meson build':
      b'The Meson build system\nVersion: 0.62.2\nSource dir: /tmp/pip-req-build-4ppusefq\nBuild dir: /tmp/pip-req-build-4ppusefq/build\nBuild type: native build\nProject name: pywm\nProject version: 0.1.0\nC compiler for the host machine: cc (gcc 11.3.0 "cc (Debian 11.3.0-3) 11.3.0")\nC linker for the host machine: cc ld.bfd 2.38.50.20220622\nHost machine cpu family: x86_64\nHost machine cpu: x86_64\nFound pkg-config: /usr/bin/pkg-config (0.29.2)\nRun-time dependency wayland-server found: YES 1.20.0\nRun-time dependency wayland-client found: YES 1.20.0\nRun-time dependency wayland-cursor found: YES 1.20.0\nRun-time dependency wayland-egl found: YES 18.1.0\nRun-time dependency wayland-protocols found: YES 1.25\nRun-time dependency xkbcommon found: YES 1.4.0\nRun-time dependency libinput found: YES 1.21.0\nRun-time dependency pixman-1 found: YES 0.40.0\nFound CMake: /usr/bin/cmake (3.23.2)\nRun-time dependency xwayland found: NO (tried pkgconfig and cmake)\nLibrary pthread found: YES\nLibrary m found: YES\n\nExecuting subproject wlroots \n\nwlroots| Project name: wlroots\nwlroots| Project version: 0.16.0\nwlroots| C compiler for the host machine: cc (gcc 11.3.0 "cc (Debian 11.3.0-3) 11.3.0")\nwlroots| C linker for the host machine: cc ld.bfd 2.38.50.20220622\nwlroots| Compiler for C supports arguments -Wundef: YES\nwlroots| Compiler for C supports arguments -Wlogical-op: YES\nwlroots| Compiler for C supports arguments -Wmissing-include-dirs: YES\nwlroots| Compiler for C supports arguments -Wold-style-definition: YES\nwlroots| Compiler for C supports arguments -Wpointer-arith: YES\nwlroots| Compiler for C supports arguments -Winit-self: YES\nwlroots| Compiler for C supports arguments -Wstrict-prototypes: YES\nwlroots| Compiler for C supports arguments -Wimplicit-fallthrough=2: YES\nwlroots| Compiler for C supports arguments -Wendif-labels: YES\nwlroots| Compiler for C supports arguments -Wstrict-aliasing=2: YES\nwlroots| Compiler for C supports arguments -Woverflow: YES\nwlroots| Compiler for C supports arguments -Wmissing-prototypes: YES\nwlroots| Compiler for C supports arguments -Walloca: YES\nwlroots| Compiler for C supports arguments -Wno-missing-braces: YES\nwlroots| Compiler for C supports arguments -Wno-missing-field-initializers: YES\nwlroots| Compiler for C supports arguments -Wno-unused-parameter: YES\nwlroots| Compiler for C supports arguments -fmacro-prefix-map=/prefix/to/hide=: YES\nwlroots| Dependency wayland-server found: YES 1.20.0 (cached)\nwlroots| Run-time dependency libdrm found: YES 2.4.110\nwlroots| Run-time dependency gbm found: YES 22.0.5\nwlroots| Dependency xkbcommon found: YES 1.4.0 (cached)\nwlroots| Run-time dependency libudev found: YES 251\nwlroots| Dependency pixman-1 found: YES 0.40.0 (cached)\nwlroots| Library m found: YES\nwlroots| Library rt found: YES\nwlroots| Dependency wayland-protocols found: YES 1.25 (cached)\nwlroots| Found pkg-config: /usr/bin/pkg-config (0.29.2)\nwlroots| Build-time dependency wayland-scanner found: YES 1.20.0\nwlroots| Program /usr/bin/wayland-scanner found: YES (/usr/bin/wayland-scanner)\nwlroots| Run-time dependency egl found: YES 1.5\nwlroots| Run-time dependency glesv2 found: YES 3.2\nwlroots| Run-time dependency vulkan found: NO (tried pkgconfig and system)\nwlroots| Message: Required for vulkan renderer support.\nwlroots| Message: Required for vulkan renderer support.\nwlroots| Dependency pixman-1 found: YES 0.40.0 (cached)\nwlroots| Checking for function "gbm_bo_get_fd_for_plane" with dependency gbm: YES\nwlroots| Dependency libinput found: YES 1.21.0 (cached)\nwlroots| Run-time dependency xcb found: YES 1.14\nwlroots| Run-time dependency xcb-dri3 found: NO (tried pkgconfig and cmake)\nwlroots| Message: Required for X11 backend support.\nwlroots| Message: Required for X11 backend support.\nwlroots| Dependency wayland-client found: YES 1.20.0 (cached)\nwlroots| Run-time dependency libseat found: NO (tried pkgconfig and cmake)\nwlroots| Looking for a fallback subproject for the dependency libseat\n\nsubprojects/wlroots/backend/session/meson.build:1:0: ERROR: Neither a subproject directory nor a seatd.wrap file was found.\n\nA full log can be found at /tmp/pip-req-build-4ppusefq/build/meson-logs/meson-log.txt\n'
      b''
      [end of output]
```

**Comment by eli-schwartz** [comment]
https://github.com/jbuchermn/pywm/blob/6cd58ed216fe5b7448e1dd9321dfc05f591b0fe5/setup.py#L8-L9

This prints the repr of a bytestring which is kind of... bad... for reading. After copy/pasting the line into a python shell and using `print(var.decode('utf-8'))` I get something halfway sane as a status:
```
The Meson build system
Version: 0.62.2
Source dir: /tmp/pip-req-build-4ppusefq
Build dir: /tmp/pip-req-build-4ppusefq/build
Build type: native build
Project name: pywm
Project version: 0.1.0
C compiler for the host machine: cc (gcc 11.3.0 "cc (Debian 11.3.0-3) 11.3.0")
C linker for the host machine: cc ld.bfd 2.38.50.20220622
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency wayland-server found: YES 1.20.0
Run-time dependency wayland-client found: YES 1.20.0
Run-time dependency wayland-cursor found: YES 1.20.0
Run-time dependency wayland-egl found: YES 18.1.0
Run-time dependency wayland-protocols found: YES 1.25
Run-time dependency xkbcommon found: YES 1.4.0
Run-time dependency libinput found: YES 1.21.0
Run-time dependency pixman-1 found: YES 0.40.0
Found CMake: /usr/bin/cmake (3.23.2)
Run-time dependency xwayland found: NO (tried pkgconfig and cmake)
Library pthread found: YES
Library m found: YES

Executing subproject wlroots 

wlroots| Project name: wlroots
wlroots| Project version: 0.16.0
wlroots| C compiler for the host machine: cc (gcc 11.3.0 "cc (Debian 11.3.0-3) 11.3.0")
wlroots| C linker for the host machine: cc ld.bfd 2.38.50.20220622
wlroots| Compiler for C supports arguments -Wundef: YES
wlroots| Compiler for C supports arguments -Wlogical-op: YES
wlroots| Compiler for C supports arguments -Wmissing-include-dirs: YES
wlroots| Compiler for C supports arguments -Wold-style-definition: YES
wlroots| Compiler for C supports arguments -Wpointer-arith: YES
wlroots| Compiler for C supports arguments -Winit-self: YES
wlroots| Compiler for C supports arguments -Wstrict-prototypes: YES
wlroots| Compiler for C supports arguments -Wimplicit-fallthrough=2: YES
wlroots| Compiler for C supports arguments -Wendif-labels: YES
wlroots| Compiler for C supports arguments -Wstrict-aliasing=2: YES
wlroots| Compiler for C supports arguments -Woverflow: YES
wlroots| Compiler for C supports arguments -Wmissing-prototypes: YES
wlroots| Compiler for C supports arguments -Walloca: YES
wlroots| Compiler for C supports arguments -Wno-missing-braces: YES
wlroots| Compiler for C supports arguments -Wno-missing-field-initializers: YES
wlroots| Compiler for C supports arguments -Wno-unused-parameter: YES
wlroots| Compiler for C supports arguments -fmacro-prefix-map=/prefix/to/hide=: YES
wlroots| Dependency wayland-server found: YES 1.20.0 (cached)
wlroots| Run-time dependency libdrm found: YES 2.4.110
wlroots| Run-time dependency gbm found: YES 22.0.5
wlroots| Dependency xkbcommon found: YES 1.4.0 (cached)
wlroots| Run-time dependency libudev found: YES 251
wlroots| Dependency pixman-1 found: YES 0.40.0 (cached)
wlroots| Library m found: YES
wlroots| Library rt found: YES
wlroots| Dependency wayland-protocols found: YES 1.25 (cached)
wlroots| Found pkg-config: /usr/bin/pkg-config (0.29.2)
wlroots| Build-time dependency wayland-scanner found: YES 1.20.0
wlroots| Program /usr/bin/wayland-scanner found: YES (/usr/bin/wayland-scanner)
wlroots| Run-time dependency egl found: YES 1.5
wlroots| Run-time dependency glesv2 found: YES 3.2
wlroots| Run-time dependency vulkan found: NO (tried pkgconfig and system)
wlroots| Message: Required for vulkan renderer support.
wlroots| Message: Required for vulkan renderer support.
wlroots| Dependency pixman-1 found: YES 0.40.0 (cached)
wlroots| Checking for function "gbm_bo_get_fd_for_plane" with dependency gbm: YES
wlroots| Dependency libinput found: YES 1.21.0 (cached)
wlroots| Run-time dependency xcb found: YES 1.14
wlroots| Run-time dependency xcb-dri3 found: NO (tried pkgconfig and cmake)
wlroots| Message: Required for X11 backend support.
wlroots| Message: Required for X11 backend support.
wlroots| Dependency wayland-client found: YES 1.20.0 (cached)
wlroots| Run-time dependency libseat found: NO (tried pkgconfig and cmake)
wlroots| Looking for a fallback subproject for the dependency libseat

subprojects/wlroots/backend/session/meson.build:1:0: ERROR: Neither a subproject directory nor a seatd.wrap file was found.

A full log can be found at /tmp/pip-req-build-4ppusefq/build/meson-logs/meson-log.txt
```

Two points to note:
- this project doesn't use the system wlroots: https://github.com/jbuchermn/pywm/blob/6cd58ed216fe5b7448e1dd9321dfc05f591b0fe5/meson.build#L47
- apparently libseat-dev is NOT found, because... `wlroots| Run-time dependency libseat found: NO (tried pkgconfig and cmake)`

**Comment by euglevi** [comment]
The problem was related to the Debian version of the libseat package. As soon as I updated it today, pywm got installed.
