### ISSUE TITLE
Missing dependency: wayland-server

### ISSUE THREAD

**Issue by donni-h** [jbuchermn/pywm#17]
I keep getting the same error message on both Fedora and Voidlinux.
error: subprocess-exited-with-error
 
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-xb39bncm/setup.py", line 9, in <module>
          raise Exception("Fatal: Error executing 'meson build': \n%r\n%r" % (stdout, stderr))
      Exception: Fatal: Error executing 'meson build':
      b'The Meson build system\nVersion: 0.62.2\nSource dir: /tmp/pip-req-build-xb39bncm\nBuild dir: /tmp/pip-req-build-xb39bncm/build\nBuild type: native build\nProject name: pywm\nProject version: 0.1.0\nC compiler for the host machine: cc (gcc 10.2.1 "cc (GCC) 10.2.1 20201203")\nC linker for the host machine: cc ld.bfd 2.35.1\nHost machine cpu family: x86_64\nHost machine cpu: x86_64\nFound pkg-config: /usr/bin/pkg-config (0.29.2)\nFound CMake: /usr/bin/cmake (3.22.2)\nRun-time dependency wayland-server found: NO (tried pkgconfig and cmake)\n\nmeson.build:33:0: ERROR: Dependency "wayland-server" not found, tried pkgconfig and cmake\n\nA full log can be found at /tmp/pip-req-build-xb39bncm/build/meson-logs/meson-log.txt\n'
      b''
      [end of output]
 
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
 
× Encountered error while generating package metadata.
╰─> See above for output.

On both of the machines I have Gnome and other Wayland WMs installed and made sure that all listed dependencies are pulled in. I also checked both repos, and neither contains a package calles 'wayland-server'. Is there a fix to this, as I would really love to give Newm a shot :)

**Comment by cben** [comment]
On Fedora, I have these files:
```sh
> rpm -qf /usr/lib/libwayland-server.so.0 /usr/include/wayland-server.h
libwayland-server-1.20.0-4.fc36.i686
wayland-devel-1.20.0-4.fc36.x86_64
```
so try `sudo dnf install libwayland-server wayland-devel`

**Comment by donni-h** [comment]
> On Fedora, I have e.g. these files:
> 
> ```shell
> > rpm -qf /usr/lib/libwayland-server.so.0 /usr/include/wayland-server.h
> libwayland-server-1.20.0-4.fc36.i686
> wayland-devel-1.20.0-4.fc36.x86_64
> ```
> 
> so try `sudo dnf install libwayland-server wayland-devel`

Alright, that did the job. There were a bunch of other dependencies still missing, that weren't listed in the repo. I could track them all down, except for GLESv2, is that even a thing in fedora?

**Comment by cben** [comment]
yeah, this one is pretty mysterious:
```
> rpm -qf /usr/lib64/pkgconfig/glesv2.pc
libglvnd-devel-1.4.0-2.fc36.x86_64
```
